//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesTPH
    {
        public int EMP_ID { get; set; }
        public string Name { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<int> SALARY { get; set; }
        public Nullable<double> RATE { get; set; }
        public int TYPE_EMP { get; set; }
    }
}
